-- ===========================================
-- SCRIPT MAESTRO UNIFICADO (MULTI-TENANT)
-- Base de datos completa para la app Flutter
-- Incluye: Auth, Roles, Permisos, Empresas, Sucursales, Interacciones, Reclamos
-- ===========================================

-- ===========================================
-- PARTE 0: LIMPIEZA (OPCIONAL - CUIDADO)
-- Descomentar si se quiere reiniciar la DB
-- ===========================================
-- DROP TABLE IF EXISTS reclamos CASCADE;
-- DROP TABLE IF EXISTS interacciones CASCADE;
-- DROP TABLE IF EXISTS usuario_permiso CASCADE;
-- DROP TABLE IF EXISTS permisos CASCADE;
-- DROP TABLE IF EXISTS usuarios CASCADE;
-- DROP TABLE IF EXISTS rol_capacidad CASCADE;
-- DROP TABLE IF EXISTS capacidades CASCADE;
-- DROP TABLE IF EXISTS roles CASCADE;
-- DROP TABLE IF EXISTS sucursales CASCADE;
-- DROP TABLE IF EXISTS empresas CASCADE;

-- ===========================================
-- PARTE 1: EMPRESAS Y SUCURSALES (MULTI-TENANCY)
-- ===========================================

CREATE TABLE IF NOT EXISTS empresas (
    id bigint generated by default as identity primary key,
    nombre text not null,
    codigo text unique not null, -- Identificador único para login (ej: 'empresa-a')
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    deleted_at timestamp with time zone -- Soft delete
);

CREATE TABLE IF NOT EXISTS sucursales (
    id bigint generated by default as identity primary key,
    empresa_id bigint references empresas(id) on delete cascade not null,
    nombre text not null,
    direccion text,
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    deleted_at timestamp with time zone
);

-- ===========================================
-- PARTE 2: ROLES Y CAPACIDADES
-- ===========================================

CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS capacidades (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rol_capacidad (
    rol_id INTEGER REFERENCES roles(id) ON DELETE CASCADE,
    capacidad_id INTEGER REFERENCES capacidades(id) ON DELETE CASCADE,
    PRIMARY KEY (rol_id, capacidad_id)
);

-- Insertar roles básicos
INSERT INTO roles (nombre, descripcion) VALUES
    ('super_admin', 'Dueño de la Plataforma (Acceso Total)'),
    ('admin', 'Administrador de Empresa'),
    ('gerente', 'Gerente de Sucursal'),
    ('usuario', 'Usuario regular / Staff'),
    ('cliente', 'Cliente final')
ON CONFLICT (nombre) DO NOTHING;

-- Insertar capacidades
INSERT INTO capacidades (nombre, descripcion) VALUES
    ('publicar', 'Puede publicar contenidos'),
    ('editar', 'Puede editar contenidos'),
    ('borrar', 'Puede borrar contenidos'),
    ('leer', 'Puede leer contenidos'),
    ('gestionar_empresa', 'Puede gestionar datos de la empresa')
ON CONFLICT (nombre) DO NOTHING;

-- ===========================================
-- PARTE 3: USUARIOS (CON MULTI-TENANCY)
-- ===========================================

CREATE TABLE IF NOT EXISTS usuarios (
    id uuid PRIMARY KEY,  -- Debe coincidir con auth.users.id
    email TEXT UNIQUE NOT NULL,
    nombre TEXT,
    apellido TEXT,
    telefono TEXT,
    direccion TEXT,
    documento_identidad TEXT,
    tipo_perfil TEXT NOT NULL DEFAULT 'usuario',
    rol_id INTEGER REFERENCES roles(id),
    
    -- Nuevos campos Multi-Tenant
    empresa_id bigint references empresas(id) on delete cascade,
    sucursal_id bigint references sucursales(id) on delete set null,
    
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger para crear usuario automáticamente
-- Trigger para crear usuario automáticamente (Soporta Invitaciones)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  v_invitacion record;
  v_rol_id integer;
BEGIN
  -- 1. Buscar si hay una invitación pendiente para este email
  SELECT * INTO v_invitacion FROM public.invitaciones WHERE email = NEW.email;

  IF v_invitacion IS NOT NULL THEN
     -- CASO A: TIENE INVITACIÓN -> Usar datos de la invitación
     INSERT INTO public.usuarios (id, email, nombre, apellido, telefono, direccion, documento_identidad, tipo_perfil, rol_id, empresa_id, sucursal_id)
     VALUES (
        NEW.id, 
        NEW.email, 
        COALESCE(NEW.raw_user_meta_data->>'nombre', split_part(NEW.email, '@', 1)),
        NEW.raw_user_meta_data->>'apellido',
        NEW.raw_user_meta_data->>'telefono',
        NEW.raw_user_meta_data->>'direccion',
        NEW.raw_user_meta_data->>'documento_identidad',
        'usuario', -- Perfil base
        v_invitacion.rol_id, -- Rol asignado por el admin
        v_invitacion.empresa_id, -- Empresa asignada
        v_invitacion.sucursal_id -- Sucursal asignada
     );
     
     -- Borrar la invitación ya que fue usada
     DELETE FROM public.invitaciones WHERE id = v_invitacion.id;
     
  ELSE
     -- CASO B: REGISTRO LIBRE (SIN INVITACIÓN) -> Usuario "huérfano" o default
     -- Buscamos rol default 'usuario'
     SELECT id INTO v_rol_id FROM public.roles WHERE nombre = 'usuario' LIMIT 1;
     
     INSERT INTO public.usuarios (id, email, nombre, apellido, telefono, direccion, documento_identidad, tipo_perfil, rol_id)
     VALUES (
        NEW.id, 
        NEW.email, 
        COALESCE(NEW.raw_user_meta_data->>'nombre', split_part(NEW.email, '@', 1)),
        NEW.raw_user_meta_data->>'apellido',
        NEW.raw_user_meta_data->>'telefono',
        NEW.raw_user_meta_data->>'direccion',
        NEW.raw_user_meta_data->>'documento_identidad',
        'usuario',
        v_rol_id
     );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ===========================================
-- PARTE 4: PERMISOS INDIVIDUALES
-- ===========================================

CREATE TABLE IF NOT EXISTS permisos (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS usuario_permiso (
    usuario_id uuid REFERENCES usuarios(id) ON DELETE CASCADE,
    permiso_id INTEGER REFERENCES permisos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (usuario_id, permiso_id)
);

-- Insertar permisos detallados (Migrados del sistema anterior + Nuevos)
INSERT INTO permisos (nombre, descripcion) VALUES
    ('acceso_panel', 'Acceso al panel principal'),
    ('ver_reportes', 'Permite ver reportes'),
    ('editar_usuarios', 'Permite editar usuarios'),
    ('crear_usuarios', 'Permite crear usuarios'),
    ('eliminar_usuarios', 'Permite eliminar usuarios'),
    ('ver_reclamos', 'Permite ver reclamos'),
    ('gestionar_reclamos', 'Permite crear y editar reclamos'),
    ('gestionar_empresa', 'Permite gestionar datos de la empresa')
ON CONFLICT (nombre) DO NOTHING;

-- ===========================================
-- PARTE 5: INTERACCIONES Y RECLAMOS
-- ===========================================

CREATE TABLE IF NOT EXISTS interacciones (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users not null, -- El usuario que REALIZA la acción (o el cliente afectado)
  empresa_id bigint references empresas(id) on delete cascade, -- Aislamiento
  tipo text not null, 
  descripcion text,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS reclamos (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users not null,
  empresa_id bigint references empresas(id) on delete cascade, -- Aislamiento
  sucursal_id bigint references sucursales(id) on delete set null,
  titulo text not null,
  descripcion text,
  estado text not null default 'pendiente',
  prioridad text default 'media',
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_actualizacion timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS invitaciones (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    email text UNIQUE NOT NULL,
    empresa_id bigint REFERENCES empresas(id) ON DELETE CASCADE NOT NULL,
    sucursal_id bigint REFERENCES sucursales(id) ON DELETE SET NULL,
    rol_id integer REFERENCES roles(id) NOT NULL,
    creado_por uuid REFERENCES auth.users,
    fecha_creacion timestamptz DEFAULT now()
);

-- ===========================================
-- PARTE 6: ROW LEVEL SECURITY (RLS) - EL CORAZÓN DE LA SEGURIDAD
-- ===========================================

-- Habilitar RLS
ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE sucursales ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE interacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamos ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE capacidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE rol_capacidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE permisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_permiso ENABLE ROW LEVEL SECURITY;

-- Función auxiliar para obtener la empresa del usuario actual
CREATE OR REPLACE FUNCTION public.mi_empresa_id()
RETURNS bigint AS $$
BEGIN
  RETURN (SELECT empresa_id FROM usuarios WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Función auxiliar para verificar si es Super Admin (Global)
CREATE OR REPLACE FUNCTION public.es_super_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM usuarios 
    WHERE id = auth.uid() 
    AND tipo_perfil = 'super_admin' -- Ojo: definir este perfil
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- === POLICIES: EMPRESAS ===
-- Un usuario solo ve su propia empresa
CREATE POLICY "Ver propia empresa" ON empresas
FOR SELECT USING (id = public.mi_empresa_id() OR public.es_super_admin());

CREATE POLICY "Super Admin gestiona empresas" ON empresas
FOR ALL USING (public.es_super_admin());

-- === POLICIES: SUCURSALES ===
-- Un usuario ve las sucursales de su empresa
CREATE POLICY "Ver sucursales de mi empresa" ON sucursales
FOR SELECT USING (empresa_id = public.mi_empresa_id() OR public.es_super_admin());

CREATE POLICY "Super Admin gestiona sucursales" ON sucursales
FOR ALL USING (public.es_super_admin());

CREATE POLICY "Admins gestionan sucursales de su empresa" ON sucursales
FOR ALL USING (
  empresa_id = public.mi_empresa_id() 
  AND (
    SELECT nombre FROM roles WHERE id = (
      SELECT rol_id FROM usuarios WHERE id = auth.uid()
    )
  ) = 'admin'
);

-- === POLICIES: USUARIOS ===
-- Un usuario ve a otros usuarios DE SU MISMA EMPRESA
CREATE POLICY "Ver usuarios de mi empresa" ON usuarios
FOR SELECT USING (empresa_id = public.mi_empresa_id() OR auth.uid() = id OR public.es_super_admin());

CREATE POLICY "Super Admin gestiona usuarios" ON usuarios
FOR ALL USING (public.es_super_admin());

CREATE POLICY "Admins actualizan usuarios de su empresa" ON usuarios
FOR UPDATE USING (
  empresa_id = public.mi_empresa_id() 
  AND (
    SELECT nombre FROM roles WHERE id = (
      SELECT rol_id FROM usuarios WHERE id = auth.uid()
    )
  ) = 'admin'
);

-- === POLICIES: INTERACCIONES ===
CREATE POLICY "Ver interacciones de mi empresa" ON interacciones
FOR SELECT USING (empresa_id = public.mi_empresa_id());

CREATE POLICY "Crear interacciones en mi empresa" ON interacciones
FOR INSERT WITH CHECK (empresa_id = public.mi_empresa_id());

-- === POLICIES: RECLAMOS ===
CREATE POLICY "Ver reclamos de mi empresa" ON reclamos
FOR SELECT USING (empresa_id = public.mi_empresa_id());

CREATE POLICY "Gestionar reclamos de mi empresa" ON reclamos
FOR ALL USING (empresa_id = public.mi_empresa_id());

-- === POLICIES: INVITACIONES ===
CREATE POLICY "Ver invitaciones de mi empresa" ON invitaciones
FOR SELECT USING (empresa_id = public.mi_empresa_id() OR public.es_super_admin());

CREATE POLICY "Crear invitaciones para mi empresa" ON invitaciones
FOR INSERT WITH CHECK (empresa_id = public.mi_empresa_id() OR public.es_super_admin());

CREATE POLICY "Borrar invitaciones de mi empresa" ON invitaciones
FOR DELETE USING (empresa_id = public.mi_empresa_id() OR public.es_super_admin());

-- === POLICIES: METADATA (ROLES, PERMISOS) ===
-- Roles: Lectura pública, gestión solo admin
CREATE POLICY "Ver roles" ON roles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins gestionan roles" ON roles FOR ALL USING (public.es_super_admin());

-- Capacidades: Lectura pública, gestión solo admin
CREATE POLICY "Ver capacidades" ON capacidades FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins gestionan capacidades" ON capacidades FOR ALL USING (public.es_super_admin());

-- Permisos: Lectura pública, gestión solo admin
CREATE POLICY "Ver permisos" ON permisos FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins gestionan permisos" ON permisos FOR ALL USING (public.es_super_admin());

-- Usuario Permiso: Ver propios, gestión solo admin
CREATE POLICY "Ver mis permisos" ON usuario_permiso FOR SELECT USING (usuario_id = auth.uid());
CREATE POLICY "Admins gestionan permisos usuarios" ON usuario_permiso FOR ALL USING (public.es_super_admin());

-- Rol Capacidad: Lectura pública, gestión solo admin
CREATE POLICY "Ver rol_capacidad" ON rol_capacidad FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins gestionan rol_capacidad" ON rol_capacidad FOR ALL USING (public.es_super_admin());

-- ===========================================
-- FIN DEL SCRIPT
-- ===========================================
-- ===========================================
-- SISTEMA DE MÓDULOS (MARKETPLACE)
-- Permite activar/desactivar funcionalidades por empresa
-- ===========================================

-- 1. Tabla de Módulos (Catálogo)
CREATE TABLE IF NOT EXISTS modulos (
    id SERIAL PRIMARY KEY,
    codigo TEXT UNIQUE NOT NULL, -- ej: 'reclamos', 'crm'
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10, 2) DEFAULT 0.00, -- Para futuro cobro
    icono TEXT, -- Nombre del icono (ej: 'report_problem')
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Módulos por Empresa (Activaciones)
CREATE TABLE IF NOT EXISTS empresa_modulos (
    id SERIAL PRIMARY KEY,
    empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE NOT NULL,
    modulo_id INTEGER REFERENCES modulos(id) ON DELETE CASCADE NOT NULL,
    fecha_activacion TIMESTAMPTZ DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ, -- NULL = De por vida / Suscripción activa
    activo BOOLEAN DEFAULT TRUE,
    UNIQUE(empresa_id, modulo_id)
);

-- 3. RLS Policies

-- Habilitar RLS
ALTER TABLE modulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE empresa_modulos ENABLE ROW LEVEL SECURITY;

-- Policies: MODULOS
-- Todos los usuarios autenticados pueden ver el catálogo de módulos
CREATE POLICY "Ver catálogo de módulos" ON modulos
FOR SELECT USING (auth.role() = 'authenticated');

-- Solo Super Admin puede gestionar el catálogo
CREATE POLICY "Super Admin gestiona módulos" ON modulos
FOR ALL USING (public.es_super_admin());

-- Policies: EMPRESA_MODULOS
-- Ver módulos activos de mi empresa
CREATE POLICY "Ver módulos de mi empresa" ON empresa_modulos
FOR SELECT USING (empresa_id = public.mi_empresa_id() OR public.es_super_admin());

-- Admin de empresa puede activar/desactivar módulos de SU empresa
-- (En un sistema real de pagos, esto podría estar restringido a un proceso de checkout)
CREATE POLICY "Admin gestiona módulos de su empresa" ON empresa_modulos
FOR ALL USING (
  empresa_id = public.mi_empresa_id() 
  AND (
    SELECT nombre FROM roles WHERE id = (
      SELECT rol_id FROM usuarios WHERE id = auth.uid()
    )
  ) = 'admin'
);

CREATE POLICY "Super Admin gestiona empresa_modulos" ON empresa_modulos
FOR ALL USING (public.es_super_admin());

-- 4. Datos Semilla (Módulos Iniciales)
INSERT INTO modulos (codigo, nombre, descripcion, icono, precio) VALUES
('reclamos', 'Sistema de Reclamos', 'Permite a tus clientes y empleados registrar y gestionar reclamos.', 'report_problem', 0.00),
('interacciones', 'CRM de Interacciones', 'Registra cada punto de contacto con tus clientes.', 'history', 0.00),
('inventario', 'Gestión de Inventario', 'Control de stock y productos (Próximamente).', 'inventory', 10.00)
ON CONFLICT (codigo) DO NOTHING;
-- ===========================================
-- SISTEMA DE MÓDULOS GRANULARES
-- ===========================================

-- 1. Tabla para activación por SUCURSAL
CREATE TABLE IF NOT EXISTS sucursal_modulos (
    id SERIAL PRIMARY KEY,
    sucursal_id INTEGER REFERENCES sucursales(id) ON DELETE CASCADE,
    modulo_codigo TEXT REFERENCES modulos(codigo) ON DELETE CASCADE,
    fecha_activacion TIMESTAMPTZ DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE,
    UNIQUE(sucursal_id, modulo_codigo)
);

-- 2. Tabla para activación por USUARIO
CREATE TABLE IF NOT EXISTS usuario_modulos (
    id SERIAL PRIMARY KEY,
    usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
    modulo_codigo TEXT REFERENCES modulos(codigo) ON DELETE CASCADE,
    fecha_activacion TIMESTAMPTZ DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE,
    UNIQUE(usuario_id, modulo_codigo)
);

-- ===========================================
-- RLS POLICIES
-- ===========================================

ALTER TABLE sucursal_modulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_modulos ENABLE ROW LEVEL SECURITY;

-- POLICY: Ver módulos de mi sucursal
-- Permitir si soy usuario de esa sucursal O si soy admin de la empresa a la que pertenece la sucursal
CREATE POLICY "Ver módulos de mi sucursal" ON sucursal_modulos
    FOR SELECT
    USING (
        sucursal_id IN (
            SELECT sucursal_id FROM usuarios WHERE id = auth.uid()
        )
        OR
        sucursal_id IN (
            SELECT id FROM sucursales WHERE empresa_id IN (
                SELECT empresa_id FROM usuarios WHERE id = auth.uid() AND (tipo_perfil = 'admin' OR tipo_perfil = 'super_admin')
            )
        )
    );

-- POLICY: Admin gestiona módulos de sucursales
CREATE POLICY "Admin gestiona módulos de sucursales" ON sucursal_modulos
    FOR ALL
    USING (
        sucursal_id IN (
            SELECT id FROM sucursales WHERE empresa_id IN (
                SELECT empresa_id FROM usuarios WHERE id = auth.uid() AND (tipo_perfil = 'admin' OR tipo_perfil = 'super_admin')
            )
        )
    );

-- POLICY: Ver módulos propios (usuario)
CREATE POLICY "Ver módulos propios" ON usuario_modulos
    FOR SELECT
    USING (
        usuario_id = auth.uid()
        OR
        usuario_id IN (
            SELECT id FROM usuarios WHERE empresa_id IN (
                SELECT empresa_id FROM usuarios WHERE id = auth.uid() AND (tipo_perfil = 'admin' OR tipo_perfil = 'super_admin')
            )
        )
    );

-- POLICY: Admin gestiona módulos de usuarios
CREATE POLICY "Admin gestiona módulos de usuarios" ON usuario_modulos
    FOR ALL
    USING (
        usuario_id IN (
            SELECT id FROM usuarios WHERE empresa_id IN (
                SELECT empresa_id FROM usuarios WHERE id = auth.uid() AND (tipo_perfil = 'admin' OR tipo_perfil = 'super_admin')
            )
        )
    );
-- ===========================================
-- MIGRACIÓN: PRECIOS GRANULARES Y DASHBOARD
-- ===========================================

-- 1. Agregar columna de precio personalizado a las tablas granulares
ALTER TABLE sucursal_modulos 
ADD COLUMN IF NOT EXISTS precio_personalizado DECIMAL(10, 2) DEFAULT NULL;

ALTER TABLE usuario_modulos 
ADD COLUMN IF NOT EXISTS precio_personalizado DECIMAL(10, 2) DEFAULT NULL;

-- 2. Agregar módulo 'dashboard' al catálogo
-- Este módulo controlará la visibilidad de los widgets principales
INSERT INTO modulos (codigo, nombre, descripcion, icono, precio) 
VALUES ('dashboard', 'Dashboard Principal', 'Visualización de métricas y resúmenes.', 'dashboard', 0.00)
ON CONFLICT (codigo) DO NOTHING;

-- 3. Asegurar que el dashboard esté activo por defecto para la empresa demo (opcional, pero útil)
-- Si ya existe la empresa demo (id 1 usually), se lo activamos.
DO $$
DECLARE
    v_empresa_id bigint;
    v_modulo_id integer;
BEGIN
    SELECT id INTO v_empresa_id FROM empresas WHERE codigo = 'demo';
    SELECT id INTO v_modulo_id FROM modulos WHERE codigo = 'dashboard';

    IF v_empresa_id IS NOT NULL AND v_modulo_id IS NOT NULL THEN
        INSERT INTO empresa_modulos (empresa_id, modulo_id, activo)
        VALUES (v_empresa_id, v_modulo_id, true)
        ON CONFLICT (empresa_id, modulo_id) DO NOTHING;
    END IF;
END $$;
