-- =============================================
-- SCHEMA SINGLE-TENANT COMPLETO
-- Base de datos para Automate Dashboard
-- Versión: 1.0
-- Fecha: 2025-12-19
-- =============================================
-- 
-- Características:
-- - Una sola empresa (single-tenant)
-- - Módulos activables por sucursal
-- - RLS simplificado
-- - Sistema completo de gestión
--
-- =============================================

BEGIN;

-- ==========================================
-- PARTE 1: EMPRESA Y SUCURSALES
-- ==========================================

CREATE TABLE empresas (
    id bigint generated by default as identity primary key,
    nombre text not null,
    codigo text unique not null,
    logo_url text,
    color_tema text default '#2196F3',
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    deleted_at timestamp with time zone
);

-- Insertar empresa única
INSERT INTO empresas (id, nombre, codigo, fecha_creacion)
VALUES (1, 'Mi Empresa', 'default', NOW());

CREATE TABLE empresa_branding (
    id SERIAL PRIMARY KEY,
    empresa_id INTEGER REFERENCES empresas(id) ON DELETE CASCADE UNIQUE NOT NULL,
    
    -- Colores (formato hex: #RRGGBB)
    color_primario VARCHAR(7) DEFAULT '#1976D2' NOT NULL,
    color_secundario VARCHAR(7) DEFAULT '#DC004E' NOT NULL,
    color_acento VARCHAR(7) DEFAULT '#FFC107' NOT NULL,
    
    -- Logo URL (Supabase Storage)
    logo_url TEXT,
    logo_light_url TEXT,
    favicon_url TEXT,
    
    -- Tipografía
    fuente_primaria VARCHAR(50) DEFAULT 'Roboto' NOT NULL,
    
    -- Dark Mode
    dark_mode_habilitado BOOLEAN DEFAULT true NOT NULL,
    color_primario_dark VARCHAR(7),
    color_secundario_dark VARCHAR(7),
    
    -- Colores adicionales light
    color_fondo VARCHAR(7) DEFAULT '#FFFFFF',
    color_texto VARCHAR(7) DEFAULT '#1F2937',
    color_error VARCHAR(7) DEFAULT '#EF4444',
    color_exito VARCHAR(7) DEFAULT '#10B981',
    color_advertencia VARCHAR(7) DEFAULT '#F59E0B',
    color_info VARCHAR(7) DEFAULT '#3B82F6',
    
    -- Colores adicionales dark
    color_fondo_dark VARCHAR(7) DEFAULT '#1F2937',
    color_texto_dark VARCHAR(7) DEFAULT '#F9FAFB',
    color_error_dark VARCHAR(7) DEFAULT '#F87171',
    color_exito_dark VARCHAR(7) DEFAULT '#34D399',
    color_advertencia_dark VARCHAR(7) DEFAULT '#FBBF24',
    color_info_dark VARCHAR(7) DEFAULT '#60A5FA',
    
    -- Timestamps
    fecha_creacion TIMESTAMP DEFAULT NOW() NOT NULL,
    actualizado_en TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_empresa_branding_empresa ON empresa_branding(empresa_id);

-- Insertar branding por defecto
INSERT INTO empresa_branding (empresa_id, fecha_creacion, actualizado_en)
VALUES (1, NOW(), NOW());

CREATE TABLE sucursales (
    id bigint generated by default as identity primary key,
    empresa_id bigint references empresas(id) on delete cascade not null default 1,
    nombre text not null,
    direccion text,
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    deleted_at timestamp with time zone
);

-- Insertar sucursal principal
INSERT INTO sucursales (empresa_id, nombre, direccion, fecha_creacion)
VALUES (1, 'Casa Matriz', 'Dirección principal', NOW());

-- ==========================================
-- PARTE 2: ROLES Y CAPACIDADES
-- ==========================================

CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE capacidades (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE rol_capacidad (
    rol_id INTEGER REFERENCES roles(id) ON DELETE CASCADE,
    capacidad_id INTEGER REFERENCES capacidades(id) ON DELETE CASCADE,
    PRIMARY KEY (rol_id, capacidad_id)
);

-- Insertar roles (sin super_admin)
INSERT INTO roles (nombre, descripcion) VALUES
    ('admin', 'Administrador de Empresa'),
    ('gerente', 'Gerente de Sucursal'),
    ('usuario', 'Usuario regular / Staff'),
    ('cliente', 'Cliente final')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO capacidades (nombre, descripcion) VALUES
    ('publicar', 'Puede publicar contenidos'),
    ('editar', 'Puede editar contenidos'),
    ('borrar', 'Puede borrar contenidos'),
    ('leer', 'Puede leer contenidos'),
    ('gestionar_empresa', 'Puede gestionar datos de la empresa')
ON CONFLICT (nombre) DO NOTHING;

-- Asignar capacidades a roles
INSERT INTO rol_capacidad (rol_id, capacidad_id)
SELECT r.id, c.id FROM roles r CROSS JOIN capacidades c 
WHERE r.nombre = 'admin' AND c.nombre IN ('gestionar_empresa', 'editar', 'borrar', 'leer', 'publicar')
ON CONFLICT (rol_id, capacidad_id) DO NOTHING;

INSERT INTO rol_capacidad (rol_id, capacidad_id)
SELECT r.id, c.id FROM roles r CROSS JOIN capacidades c 
WHERE r.nombre = 'gerente' AND c.nombre IN ('editar', 'leer', 'publicar')
ON CONFLICT (rol_id, capacidad_id) DO NOTHING;

INSERT INTO rol_capacidad (rol_id, capacidad_id)
SELECT r.id, c.id FROM roles r CROSS JOIN capacidades c 
WHERE r.nombre = 'usuario' AND c.nombre IN ('leer', 'publicar')
ON CONFLICT (rol_id, capacidad_id) DO NOTHING;

INSERT INTO rol_capacidad (rol_id, capacidad_id)
SELECT r.id, c.id FROM roles r CROSS JOIN capacidades c 
WHERE r.nombre = 'cliente' AND c.nombre = 'leer'
ON CONFLICT (rol_id, capacidad_id) DO NOTHING;

-- ==========================================
-- PARTE 3: USUARIOS
-- ==========================================

CREATE TABLE usuarios (
    id uuid PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    username TEXT,
    nombre TEXT,
    apellido TEXT,
    telefono TEXT,
    direccion TEXT,
    documento_identidad TEXT,
    tipo_perfil TEXT NOT NULL DEFAULT 'usuario',
    rol_id INTEGER REFERENCES roles(id),
    empresa_id bigint references empresas(id) on delete cascade default 1,
    sucursal_id bigint references sucursales(id) on delete set null,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger para auto-crear usuarios
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  v_rol_id integer;
BEGIN
  -- Obtener rol 'usuario' por defecto
  SELECT id INTO v_rol_id FROM public.roles WHERE nombre = 'usuario' LIMIT 1;
  
  -- Insertar usuario con empresa_id = 1 (hardcodeado)
  INSERT INTO public.usuarios (
    id, 
    email, 
    username, 
    nombre, 
    apellido, 
    telefono, 
    direccion, 
    documento_identidad, 
    tipo_perfil, 
    rol_id,
    empresa_id
  ) VALUES (
    NEW.id, 
    NEW.email, 
    NEW.raw_user_meta_data->>'username', 
    COALESCE(NEW.raw_user_meta_data->>'nombre', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'apellido',
    NEW.raw_user_meta_data->>'telefono',
    NEW.raw_user_meta_data->>'direccion',
    NEW.raw_user_meta_data->>'documento_identidad',
    'usuario',
    v_rol_id,
    1  -- Hardcodeado: empresa única
  );
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- PARTE 4: PERMISOS INDIVIDUALES
-- ==========================================

CREATE TABLE permisos (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE usuario_permiso (
    usuario_id uuid REFERENCES usuarios(id) ON DELETE CASCADE,
    permiso_id INTEGER REFERENCES permisos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (usuario_id, permiso_id)
);

INSERT INTO permisos (nombre, descripcion) VALUES
    ('acceso_panel', 'Acceso al panel principal'),
    ('ver_reportes', 'Permite ver reportes'),
    ('editar_usuarios', 'Permite editar usuarios'),
    ('crear_usuarios', 'Permite crear usuarios'),
    ('eliminar_usuarios', 'Permite eliminar usuarios'),
    ('ver_reclamos', 'Permite ver reclamos'),
    ('gestionar_reclamos', 'Permite crear y editar reclamos'),
    ('gestionar_empresa', 'Permite gestionar datos de la empresa')
ON CONFLICT (nombre) DO NOTHING;

-- ==========================================
-- PARTE 5: TIPOS DINÁMICOS
-- ==========================================

CREATE TABLE tipos_reclamo (
    id SERIAL PRIMARY KEY,
    empresa_id bigint REFERENCES empresas(id) ON DELETE CASCADE NOT NULL default 1,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    prioridad_default TEXT DEFAULT 'media',
    campos_requeridos JSONB DEFAULT '[]',
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(empresa_id, nombre)
);

CREATE TABLE tipos_interaccion (
    id SERIAL PRIMARY KEY,
    empresa_id bigint REFERENCES empresas(id) ON DELETE CASCADE NOT NULL default 1,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(empresa_id, nombre)
);

-- Datos semilla
INSERT INTO tipos_reclamo (empresa_id, nombre, descripcion, prioridad_default, activo)
VALUES
  (1, 'General', 'Reclamo general', 'media', true),
  (1, 'Técnico', 'Problema técnico o de producto', 'alta', true),
  (1, 'Servicio', 'Atención al cliente', 'media', true),
  (1, 'Facturación', 'Problema con facturación o cobros', 'alta', true)
ON CONFLICT (empresa_id, nombre) DO NOTHING;

INSERT INTO tipos_interaccion (empresa_id, nombre, descripcion, activo)
VALUES
  (1, 'Llamada', 'Llamada telefónica', true),
  (1, 'Email', 'Correo electrónico', true),
  (1, 'Reunión', 'Reunión presencial o virtual', true),
  (1, 'WhatsApp', 'Mensaje por WhatsApp', true),
  (1, 'Visita', 'Visita al cliente', true)
ON CONFLICT (empresa_id, nombre) DO NOTHING;

-- ==========================================
-- PARTE 6: INTERACCIONES Y RECLAMOS
-- ==========================================

CREATE TABLE interacciones (
    id bigint generated by default as identity primary key,
    usuario_id uuid references auth.users not null,
    empresa_id bigint references empresas(id) on delete cascade default 1,
    tipo text not null,
    tipo_interaccion_id integer REFERENCES tipos_interaccion(id) ON DELETE SET NULL,
    descripcion text,
    datos_extra jsonb,
    fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE reclamos (
    id bigint generated by default as identity primary key,
    usuario_id uuid references auth.users not null,
    empresa_id bigint references empresas(id) on delete cascade default 1,
    sucursal_id bigint references sucursales(id) on delete set null,
    cliente_id bigint,
    tipo_reclamo_id integer REFERENCES tipos_reclamo(id) ON DELETE SET NULL,
    titulo text not null,
    descripcion text,
    estado text not null default 'pendiente',
    prioridad text default 'media',
    datos_extra jsonb,
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    fecha_actualizacion timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE historial_reclamos (
    id bigint generated by default as identity primary key,
    reclamo_id bigint references reclamos(id) on delete cascade,
    usuario_id uuid references auth.users,
    tipo_accion text,
    descripcion text,
    fecha timestamp with time zone default now(),
    datos_cambio jsonb
);

-- ==========================================
-- PARTE 7: CLIENTES
-- ==========================================

CREATE TABLE clientes (
    id bigint generated by default as identity primary key,
    empresa_id bigint references empresas(id) on delete cascade default 1,
    sucursal_id bigint references sucursales(id) on delete set null,
    tipo_cliente text not null,
    nombre text,
    apellido text,
    razon_social text,
    documento_identidad text,
    email text,
    telefono text,
    direccion text,
    notas text,
    estado text default 'activo',
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    actualizado_en timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FK para reclamos -> clientes
ALTER TABLE reclamos ADD CONSTRAINT reclamos_cliente_id_fkey 
FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;

-- Trigger para actualizar fecha
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.actualizado_en = now(); 
   RETURN NEW;
END;
$$ language 'plpgsql' SECURITY DEFINER SET search_path = pg_catalog, public;

CREATE TRIGGER update_clientes_modtime
    BEFORE UPDATE ON clientes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- PARTE 8: MÓDULOS (MARKETPLACE)
-- ==========================================

CREATE TABLE modulos (
    id SERIAL PRIMARY KEY,
    codigo TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10, 2) DEFAULT 0.00,
    icono TEXT,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE sucursal_modulos (
    id SERIAL PRIMARY KEY,
    sucursal_id INTEGER REFERENCES sucursales(id) ON DELETE CASCADE,
    modulo_codigo TEXT REFERENCES modulos(codigo) ON DELETE CASCADE,
    precio_personalizado DECIMAL(10, 2) DEFAULT NULL,
    fecha_activacion TIMESTAMPTZ DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE,
    UNIQUE(sucursal_id, modulo_codigo)
);

-- Catálogo de módulos
INSERT INTO modulos (codigo, nombre, descripcion, icono, precio) VALUES
('dashboard', 'Dashboard Principal', 'Visualización de métricas y resúmenes.', 'dashboard', 0.00),
('clientes', 'Gestión de Clientes', 'CRM completo para gestionar tu base de clientes.', 'people', 0.00),
('reclamos', 'Sistema de Reclamos', 'Permite registrar y gestionar reclamos/tickets.', 'report_problem', 0.00),
('interacciones', 'CRM de Interacciones', 'Registra cada punto de contacto con tus clientes.', 'history', 0.00),
('personal', 'Gestión de Personal', 'Administra tu equipo y empleados.', 'badge', 0.00),
('sucursales', 'Gestión de Sucursales', 'Administra múltiples ubicaciones.', 'store', 0.00),
('reportes', 'Reportes Automáticos', 'Generación automática de reportes.', 'assessment', 10.00),
('inventario', 'Gestión de Inventario', 'Control de stock y productos (Próximamente).', 'inventory', 20.00),
('speech_to_text', 'Speech-to-Text Backend', 'Transcripción de audio a texto con Whisper AI', 'mic', 30.00)
ON CONFLICT (codigo) DO NOTHING;

-- ==========================================
-- PARTE 9: SPEECH-TO-TEXT (OPCIONAL)
-- ==========================================

CREATE TABLE IF NOT EXISTS transcripciones_ejecutivo (
    id SERIAL PRIMARY KEY,
    usuario_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
    archivo_audio_url TEXT NOT NULL,
    transcripcion_completa TEXT,
    segmentos JSONB,
    duracion_segundos DECIMAL(10, 2),
    idioma VARCHAR(10) DEFAULT 'es',
    modelo_usado VARCHAR(50) DEFAULT 'whisper-1',
    diarizacion_habilitada BOOLEAN DEFAULT false,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
    procesado_en TIMESTAMPTZ,
    estado VARCHAR(20) DEFAULT 'pendiente'
);

CREATE INDEX idx_transcripciones_usuario ON transcripciones_ejecutivo(usuario_id);
CREATE INDEX idx_transcripciones_cliente ON transcripciones_ejecutivo(cliente_id);

-- ==========================================
-- PARTE 10: ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Habilitar RLS en todas las tablas
ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE sucursales ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE interacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_reclamos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_reclamo ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_interaccion ENABLE ROW LEVEL SECURITY;
ALTER TABLE empresa_branding ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE capacidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE rol_capacidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE permisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_permiso ENABLE ROW LEVEL SECURITY;
ALTER TABLE modulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE sucursal_modulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE transcripciones_ejecutivo ENABLE ROW LEVEL SECURITY;

-- Función auxiliar: es_admin
CREATE OR REPLACE FUNCTION public.es_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM usuarios u
    LEFT JOIN roles r ON u.rol_id = r.id
    WHERE u.id = auth.uid() 
    AND (
      u.tipo_perfil = 'admin'
      OR r.nombre = 'admin'
    )
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ==========================================
-- POLICIES: Simplificadas para single-tenant
-- ==========================================

-- EMPRESAS (solo lectura para todos, admin puede editar)
CREATE POLICY "select_empresas" ON empresas FOR SELECT TO authenticated USING (true);
CREATE POLICY "update_empresas" ON empresas FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));

-- SUCURSALES (todos pueden ver, admin puede gestionar)
CREATE POLICY "select_sucursales" ON sucursales FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_sucursales" ON sucursales FOR INSERT TO authenticated WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "update_sucursales" ON sucursales FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "delete_sucursales" ON sucursales FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- USUARIOS (ver propio perfil + admin ve todos)
CREATE POLICY "select_usuarios" ON usuarios FOR SELECT TO authenticated USING (id = (SELECT auth.uid()) OR (SELECT public.es_admin()));
CREATE POLICY "update_usuarios" ON usuarios FOR UPDATE TO authenticated USING (id = (SELECT auth.uid()) OR (SELECT public.es_admin())) WITH CHECK (id = (SELECT auth.uid()) OR (SELECT public.es_admin()));
CREATE POLICY "delete_usuarios" ON usuarios FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- INTERACCIONES (todos autenticados)
CREATE POLICY "select_interacciones" ON interacciones FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_interacciones" ON interacciones FOR INSERT TO authenticated WITH CHECK (true);

-- RECLAMOS (todos autenticados)
CREATE POLICY "select_reclamos" ON reclamos FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_reclamos" ON reclamos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "update_reclamos" ON reclamos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "delete_reclamos" ON reclamos FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- HISTORIAL RECLAMOS
CREATE POLICY "select_historial" ON historial_reclamos FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_historial" ON historial_reclamos FOR INSERT TO authenticated WITH CHECK (true);

-- CLIENTES (todos autenticados)
CREATE POLICY "select_clientes" ON clientes FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_clientes" ON clientes FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "update_clientes" ON clientes FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "delete_clientes" ON clientes FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- TIPOS (todos ver, admin gestiona)
CREATE POLICY "select_tipos_reclamo" ON tipos_reclamo FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_tipos_reclamo" ON tipos_reclamo FOR INSERT TO authenticated WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "update_tipos_reclamo" ON tipos_reclamo FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "delete_tipos_reclamo" ON tipos_reclamo FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

CREATE POLICY "select_tipos_interaccion" ON tipos_interaccion FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_tipos_interaccion" ON tipos_interaccion FOR INSERT TO authenticated WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "update_tipos_interaccion" ON tipos_interaccion FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "delete_tipos_interaccion" ON tipos_interaccion FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- BRANDING
CREATE POLICY "select_branding" ON empresa_branding FOR SELECT TO authenticated USING (true);
CREATE POLICY "update_branding" ON empresa_branding FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));

-- ROLES/CAPACIDADES/PERMISOS (lectura para todos)
CREATE POLICY "select_roles" ON roles FOR SELECT TO authenticated USING (true);
CREATE POLICY "select_capacidades" ON capacidades FOR SELECT TO authenticated USING (true);
CREATE POLICY "select_rol_capacidad" ON rol_capacidad FOR SELECT TO authenticated USING (true);
CREATE POLICY "select_permisos" ON permisos FOR SELECT TO authenticated USING (true);
CREATE POLICY "select_usuario_permiso" ON usuario_permiso FOR SELECT TO authenticated USING (usuario_id = (SELECT auth.uid()) OR (SELECT public.es_admin()));

-- MÓDULOS (catálogo visible para todos, admin gestiona)
CREATE POLICY "select_modulos" ON modulos FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_modulos" ON modulos FOR INSERT TO authenticated WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "update_modulos" ON modulos FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "delete_modulos" ON modulos FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- SUCURSAL_MODULOS (todos ven, admin gestiona)
CREATE POLICY "select_sucursal_modulos" ON sucursal_modulos FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_sucursal_modulos" ON sucursal_modulos FOR INSERT TO authenticated WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "update_sucursal_modulos" ON sucursal_modulos FOR UPDATE TO authenticated USING ((SELECT public.es_admin())) WITH CHECK ((SELECT public.es_admin()));
CREATE POLICY "delete_sucursal_modulos" ON sucursal_modulos FOR DELETE TO authenticated USING ((SELECT public.es_admin()));

-- TRANSCRIPCIONES (usuarios ven las suyas, admin ve todas)
CREATE POLICY "select_transcripciones" ON transcripciones_ejecutivo FOR SELECT TO authenticated USING (usuario_id = (SELECT auth.uid()) OR (SELECT public.es_admin()));
CREATE POLICY "insert_transcripciones" ON transcripciones_ejecutivo FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "update_transcripciones" ON transcripciones_ejecutivo FOR UPDATE TO authenticated USING (usuario_id = (SELECT auth.uid()) OR (SELECT public.es_admin())) WITH CHECK (usuario_id = (SELECT auth.uid()) OR (SELECT public.es_admin()));

-- ==========================================
-- PARTE 11: ÍNDICES PARA PERFORMANCE
-- ==========================================

CREATE INDEX idx_usuarios_rol_id ON usuarios(rol_id);
CREATE INDEX idx_usuarios_empresa_id ON usuarios(empresa_id);
CREATE INDEX idx_usuarios_sucursal_id ON usuarios(sucursal_id);

CREATE INDEX idx_reclamos_empresa_id ON reclamos(empresa_id);
CREATE INDEX idx_reclamos_sucursal_id ON reclamos(sucursal_id);
CREATE INDEX idx_reclamos_usuario_id ON reclamos(usuario_id);
CREATE INDEX idx_reclamos_cliente_id ON reclamos(cliente_id);
CREATE INDEX idx_reclamos_estado ON reclamos(estado);
CREATE INDEX idx_historial_reclamo_id ON historial_reclamos(reclamo_id);

CREATE INDEX idx_interacciones_empresa_id ON interacciones(empresa_id);
CREATE INDEX idx_interacciones_usuario_id ON interacciones(usuario_id);

CREATE INDEX idx_clientes_empresa_id ON clientes(empresa_id);
CREATE INDEX idx_clientes_sucursal_id ON clientes(sucursal_id);
CREATE INDEX idx_clientes_documento ON clientes(documento_identidad);

CREATE INDEX idx_sucursal_modulos_sucursal_id ON sucursal_modulos(sucursal_id);
CREATE INDEX idx_usuario_permiso_permiso_id ON usuario_permiso(permiso_id);
CREATE INDEX idx_rol_capacidad_capacidad_id ON rol_capacidad(capacidad_id);

-- ==========================================
-- PARTE 12: FUNCIONES ÚTILES
-- ==========================================

-- Función de búsqueda de reclamos
CREATE OR REPLACE FUNCTION buscar_reclamos(search_query text)
RETURNS SETOF public.reclamos
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT r.*
  FROM public.reclamos r
  LEFT JOIN public.clientes c ON r.cliente_id = c.id
  WHERE
    r.titulo ILIKE '%' || search_query || '%'
    OR r.descripcion ILIKE '%' || search_query || '%'
    OR c.nombre ILIKE '%' || search_query || '%'
    OR c.apellido ILIKE '%' || search_query || '%'
    OR c.razon_social ILIKE '%' || search_query || '%';
$$;

COMMIT;

-- ==========================================
-- RESUMEN
-- ==========================================

DO $$
DECLARE
  v_empresa record;
  v_sucursales_count int;
  v_modulos_count int;
BEGIN
  SELECT * INTO v_empresa FROM empresas WHERE id = 1;
  SELECT COUNT(*) INTO v_sucursales_count FROM sucursales WHERE empresa_id = 1;
  SELECT COUNT(*) INTO v_modulos_count FROM modulos;
  
  RAISE NOTICE '================================================';
  RAISE NOTICE 'SCHEMA SINGLE-TENANT CREADO EXITOSAMENTE';
  RAISE NOTICE '================================================';
  RAISE NOTICE 'Empresa: % (ID: %)', v_empresa.nombre, v_empresa.id;
  RAISE NOTICE 'Sucursales: %', v_sucursales_count;
  RAISE NOTICE 'Módulos en catálogo: %', v_modulos_count;
  RAISE NOTICE '================================================';
  RAISE NOTICE 'Base de datos lista para usar';
  RAISE NOTICE 'Próximo paso: Ejecutar este script en Supabase SQL Editor';
  RAISE NOTICE '================================================';
END $$;
